### ISSUE TITLE
Missing Setup requirements

### ISSUE THREAD

**Issue by bionix** [puppetlabs/puppetlabs-ntp#115]
In the README is a hyperlink in the overview for the "setup requirements", but it points to nothing and the setup part is missing.

In the "Modulefile" lists a dependency with "puppetlabs-stdlib"...

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
