### ISSUE TITLE
Remove legacy fact usage

### ISSUE THREAD

**Issue by gcoxmoz** [puppetlabs/puppetlabs-ntp#659]
## Describe the Bug
https://github.com/puppetlabs/puppetlabs-ntp/blob/47dc5397686943ca9d74c134444d7564cbdae627/manifests/config.pp#L15 - puppetlabs-ntp still uses legacy facts

## Expected Behavior
When running with `include_legacy_facts = false`, no errors should occur.

## Steps to Reproduce
- Install 7.21.0 agent
- set `include_legacy_facts = false`
- run a manifest that uses this module

## Environment
 - Version - 7.21.0
 - Platform - Linux

## Additional Context

**Comment by binford2k** [comment]
fixed in #663
