### ISSUE TITLE
Add support for Solaris

### ISSUE THREAD

**Issue by blkperl** [puppetlabs/puppetlabs-ntp#76]
I may submit a PR later but for now here are the params needed for Solaris 10. 

```
  $driftfile = '/etc/ntp.drift'
  $ntpconfig = '/etc/inet/ntp.conf'
  $ntppkg    = [ ] 
  $ntpsvc    = 'ntp'
  $statsdir  = '/var/ntp/ntpstats/'
```

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
